### ISSUE TITLE
No Module BookSoup

### ISSUE THREAD

**Issue by sandyjswl** [Buroni/booksoup#2]
Traceback (most recent call last):
  File "demo_interaction_timeline.py", line 3, in <module>
    from booksoup import BookSoup
  File "/home/sandy/Downloads/booksoup-master/booksoup/__init__.py", line 1, in <module>
    from BookSoup import BookSoup
ModuleNotFoundError: No module named 'BookSoup'

 I'm getting the following error whenever i try to run one of the demo files. Am i missing something?
Forgive me if i'm missing something.

**Comment by Buroni** [comment]
Hi Sandy, thanks for raising the issue. What version of python are you running on?

**Comment by sandyjswl** [comment]
@Buroni I'm currently running on Python 3. 3.6 to be exact.

**Comment by Buroni** [comment]
@sandyjswl I've just realised that you have a file called `init.py` inside the `booksoup` folder. This should be called `__init__.py` for python to recognise BookSoup as a module. Could you rename it and see then if it works?

**Comment by sandyjswl** [comment]
It's named __init__.py I'm attaching a screenshot of the output and the folder.
https://imgur.com/N9SOmck
https://imgur.com/wTbYx3O
